export const motivationalMessages: string[] = [
  "Believe you can and you're halfway there.",
  "The secret to getting ahead is getting started.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "The expert in anything was once a beginner.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Don't watch the clock; do what it does. Keep going.",
];

export type Resource = {
  title: string;
  url: string;
  type: 'video' | 'article' | 'book';
};

export const resources: Record<string, Resource[]> = {
  'Physics': [
    { title: 'Khan Academy - Physics', url: 'https://www.khanacademy.org/science/physics', type: 'video' },
    { title: 'The Feynman Lectures on Physics', url: 'https://www.feynmanlectures.caltech.edu/', type: 'book' },
    { title: 'HyperPhysics Concepts', url: 'http://hyperphysics.phy-astr.gsu.edu/hbase/index.html', type: 'article' },
  ],
  'Mathematics': [
    { title: '3Blue1Brown YouTube Channel', url: 'https://www.youtube.com/c/3blue1brown', type: 'video' },
    { title: 'Paul\'s Online Math Notes', url: 'https://tutorial.math.lamar.edu/', type: 'article' },
    { title: 'Calculus by Michael Spivak', url: '#', type: 'book' },
  ],
  'Biology': [
    { title: 'CrashCourse Biology', url: 'https://www.youtube.com/playlist?list=PL3EED4C1D684D3ADF', type: 'video' },
    { title: 'Campbell Biology (Book)', url: '#', type: 'book' },
    { title: 'Nature - Scitable', url: 'https://www.nature.com/scitable/', type: 'article' },
  ],
  'History': [
    { title: 'CrashCourse World History', url: 'https://www.youtube.com/playlist?list=PLBDA2E52FB1EF80C9', type: 'video' },
    { title: 'History.com', url: 'https://www.history.com/', type: 'article' },
    { title: 'Sapiens: A Brief History of Humankind', url: '#', type: 'book' },
  ]
};

// This file now only contains static data that is not generated by AI.
// The quiz data has been removed and is now generated dynamically.
